#!/usr/bin/env python3
"""Emit empty Verilog stub modules for physical-only cells (fillers, well taps,
decap/boundary cells) instantiated in a gate-level netlist but absent from the
ICS55 standard-cell simulation models.

usage: gl_stubs.py <netlist.v> <out_stubs.v> <model.v>...
"""
import re
import sys
from pathlib import Path

netlist, out, *models = sys.argv[1:]
text = Path(netlist).read_text()
used = set(re.findall(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s+[\\A-Za-z_][^\s(]*\s*\(", text, re.M))
defined = set()
for m in models:
    defined |= set(re.findall(r"^\s*module\s+([A-Za-z_][A-Za-z0-9_]*)", Path(m).read_text(), re.M))
defined |= set(re.findall(r"^\s*module\s+([A-Za-z_][A-Za-z0-9_]*)", text, re.M))
keywords = {"module", "wire", "input", "output", "assign", "reg", "inout"}
missing = sorted(c for c in used - defined - keywords if c.isupper() or c[0].isupper())
lines = ["// Generated by scripts/gl_stubs.py: physical-only cells without simulation models", "`timescale 1ns/1ps"]
for cell in missing:
    lines.append(f"module {cell} ();\nendmodule")
Path(out).write_text("\n".join(lines) + "\n")
print(f"{len(missing)} stub modules: {' '.join(missing)}")
