#!/usr/bin/env python3
"""Wrap an ECC gate-level netlist (whose vector ports were split into
`name_N` bit ports) in a module with the original RTL port list, so the RTL
testbench can instantiate it unchanged.

usage: gl_wrapper.py <netlist.v> <rtl_top.v> <top_module> <out_dir>

Writes <out_dir>/gate_level_netlist_renamed.v (netlist with the top module
renamed to <top>_gl) and <out_dir>/gl_wrapper.v (module <top> wrapping it).
"""
import re
import sys
from pathlib import Path

netlist, rtl_top, top, out_dir = sys.argv[1:5]
out_dir = Path(out_dir)

rtl = Path(rtl_top).read_text()
header = re.search(rf"module\s+{top}\s*(#\s*\((.*?)\))?\s*\((.*?)\)\s*;", rtl, re.S)
if not header:
    sys.exit(f"module {top} not found in {rtl_top}")
params = re.findall(r"parameter\s+(?:\[[^\]]+\]\s*)?([A-Za-z_]\w*)\s*=\s*([^,\n]+)", header.group(2) or "")


def literal(value: str):
    """Parameter default as a Python int, or None for macros / expressions."""
    value = re.sub(r"//.*", "", value).strip()
    m = re.match(r"^(?:\d+'[bdh])?([0-9a-fA-F_]+)$", value)
    if not m:
        return None
    base = {"'b": 2, "'d": 10, "'h": 16}.get(value[value.find("'"):value.find("'") + 2], 10) if "'" in value else 10
    try:
        return int(m.group(1).replace("_", ""), base)
    except ValueError:
        return None


params = [(p, v if literal(v) is not None else "0") for p, v in params]
ports = []
for m in re.finditer(r"(input|output|inout)\s+(?:wire|reg|logic)?\s*(\[[^\]]+\])?\s*([A-Za-z_]\w*)", header.group(3)):
    direction, rng, name = m.groups()
    width = 1
    if rng:
        hi, lo = re.match(r"\[\s*(.+?)\s*:\s*(.+?)\s*\]", rng).groups()
        env = {p: literal(v) for p, v in params}
        width = eval(hi, {}, env) - eval(lo, {}, env) + 1
    ports.append((direction, width, name))

net = Path(netlist).read_text()
net_ports = set(re.findall(r"^\s*(?:input|output|inout)\s+(?:\[[^\]]+\]\s*)?([A-Za-z_]\w*)\s*;", net, re.M))
net = re.sub(rf"\bmodule\s+{top}\b", f"module {top}_gl", net, count=1)
(out_dir / "gate_level_netlist_renamed.v").write_text(net)

lines = [f"// Generated by scripts/gl_wrapper.py: vector-port wrapper around the ECC netlist ({top}_gl)",
         "`timescale 1ns/1ps"]
plist = ", ".join(f"parameter {p} = {v.strip()}" for p, v in params)
lines.append(f"module {top}" + (f" #({plist})" if plist else "") + " (")
decls = []
for direction, width, name in ports:
    rng = f"[{width - 1}:0] " if width > 1 else ""
    decls.append(f"    {direction} wire {rng}{name}")
lines.append(",\n".join(decls))
lines.append(");")
conns = []
for direction, width, name in ports:
    if width == 1:
        if name in net_ports:
            conns.append(f"    .{name}({name})")
    else:
        for i in range(width):
            bit = f"{name}_{i}"
            if bit in net_ports:
                conns.append(f"    .{bit}({name}[{i}])")
lines.append(f"  {top}_gl dut (")
lines.append(",\n".join(conns))
lines.append("  );")
lines.append("endmodule")
(out_dir / "gl_wrapper.v").write_text("\n".join(lines) + "\n")
print(f"wrapper: {len(ports)} RTL ports, {len(conns)} netlist connections")
